<?php

trait Bipede{
    public  function courir(){
        echo "Je cours";
    }
}
abstract class Human{
    use Bipede;
    public static $population = '0';
    public $taille = '175';
    public $nom;
    public $force = "1";

    private $secret = "Dark vador est ton père";

    public function  showSize(){
        echo $this->taille;
    }
    public function marcher(){
        echo "Hey, im walking here";
    }

    public function maTaille(){
        $this->taille++;
        echo $this->taille;
    }

    public function __construct($nomDeFamille = ""){
        $this->nom = $nomDeFamille;
        echo self::$population ++."\n";
            echo "je suis née";
    }

    public function __destruct(){
        echo self::$population--."\n";
            echo "je suis mort \n";
    }

    public function setSecret($secret){
        $this->secret = $secret;
    }
    public function getSecret(){
        return $this->secret;
    }

    public function showForce(){
        echo $this->force;
    }
    public function pilosite(){
        echo "J'ai du poil";
    }
}

class Homme extends Human
{
    public $force = '2';
}

class Femme extends Human
{
    public function faireEnfant(){
        echo "oui je peux enfanter";
    }
    public function pilosite()
    {
        echo "J'ai moins de poil que les hommes"; // TODO: Change the autogenerated stub
    }
}

$marceline = new Femme();echo "\n";
$constance = new Femme();echo "\n";
$adam = new Homme();echo "\n";
$marceline->marcher(); echo "\n";
$constance->showSize(); echo "\n";
$constance->maTaille();echo "\n";
$constance->showForce();echo "\n";
$adam->marcher();echo "\n";
$adam->showForce();echo "\n";
$marceline->courir();echo "\n";
$marceline->pilosite();echo"\n";
$marceline->faireEnfant();echo "\n";
unset($marceline);echo"\n";
echo $constance->getSecret();